### ISSUE TITLE
Transformer to take key:value data and transform to json txt

### ISSUE THREAD

**Issue by bakatzir** [demisto/content#17431]
**Need**
Useful for products that require a json input for example ArcSight, Splunk, Autofocus etc..
This is to simplify something that we do with transformers now.

![image](https://user-images.githubusercontent.com/51712181/73776973-516ab880-4791-11ea-80f6-63185cdf3d79.png)

**Definition Of Done**
Script name: KeyValueToJson

argument1: name: keys
example: id,name,phone

argument2: name:values
example: (11111111,22222222),(dbot,botd),(97255555)
*The values are grouped accordingly to the key location

The result of which will be
[{"id":"1111111111", "name": dbot, "phone":"97255555" },{"id": "22222222","name":"botd"}]

As for working with context data this should look like

KeyValueToJson keys=${inputs.keyList} values=(${playbookQuery.results.value}),(${playbookQuery.results.score})

**Getting Started**
For details on how to start, refer to the [Cortex XSOAR Developer Hub](https://xsoar.pan.dev/docs/contributing/contributing#what-to-contribute)

**Comment by aburt-demisto** [comment]
@bakatzir Are you taking this? I can take this tonight.

**Comment by bakatzir** [comment]
> @bakatzir Are you taking this? I can take this tonight.

I'm merely opening and triaging these request. Feel free to take any of the open non assigned issues in this repo, and link to them your PR. Our contribution team knows about them.

**Comment by bakatzir** [comment]
This is my wrong doing. Is the DoD is lacking a connection to an actual use case, we do not know if accepting this contrib will have value to a customer. closing this external issue as non valid.
