### ISSUE TITLE
[IoTSecurity] !iot-security-get-device" to be specified by IP instead of just MAC

### ISSUE THREAD

**Issue by bakatzir** [demisto/content#17703]
**Need**
 IoT API  does support IP address lookups, but it's not part of the integration. 
 
 **API ref**
https://docs.paloaltonetworks.com/iot/iot-security-api-reference/iot-security-api/get-device-details-per-ip-address.html

**Comment by Hruuttila** [comment]
@bakatzir this was implemented by the pull request 17702. I think we can close this one and the ones linked to the same request.

**Comment by aburt-demisto** [comment]
Implemented in iot-security-get-device-by-ip, this can be closed @bakatzir

**Comment by bakatzir** [comment]
Thank you Harri for making this contribution.
