### ISSUE TITLE
[URLScan] Add the "unlisted" scan argument

### ISSUE THREAD

**Issue by bakatzir** [demisto/content#17721]
**Need**
As you can see here https://urlscan.io/pricing/ URLScan offers private, unlisted and public scans. 
The urlscan integration offers currently unfortunately only "private" and "public". We would like to have also the "unlisted" mode because this is a great tradeoff regarding pricing vs data visibility. This should be very easily to implement, since visibility can be already set in the integration, it just offers currently public and private.

**API ref**
https://urlscan.io/docs/api/ 

**Definition of Done**
The `url` command has [currently](https://xsoar.pan.dev/docs/reference/integrations/urlscanio) the arg: `public - Whether the submission will be public or private`
Deprecate it, and add the argument `scan_visibility` instead with 3 options: public, unlisted, private

**Comment by aburt-demisto** [comment]
This looks possible, but only for the integration command in the URLscan integration. Removing the "public" tag would be a breaking change. Perhaps they can run in parallel and the "scan_visibility" takes precedence  over the "public" command?

**Comment by bakatzir** [comment]
Indeed. the ask is to merely deprecate the `public` argument. If the `scan_visibility` argument will be used, it will take precedence, as you've suggested, over the `public` argument.

**Comment by aburt-demisto** [comment]
Would this need to be done for EVERY integration that supports the `url` command?

**Comment by bakatzir** [comment]
No. as this functionality is only available for the URLScan product. For this reason, I would suggest giving the new argument the same defaultvalue as of the `public` - which is true/public.
