### ISSUE TITLE
Teams Integration - Unable to send notifications to specific users

### ISSUE THREAD

**Issue by rpriyanka-sa** [demisto/content#18957]
I am facing two issues with MS Teams:

1. In customer's tenant:
MS Teams is integrated. We are getting health check as operational and were able to create a channel and send notification to the channel. However, whenever we try to interact with a team member, we get one of the two errors:
- ValueError: Team member vipul@vz3xp.onmicrosoft.com was not found
    ![Uploading Screenshot 2022-05-09 at 4.34.12 PM.png…]()
- ValueError: Error in API call to Microsoft Teams: [400] - BadRequest: Operation not supported for this Channel
    ![Uploading Screenshot 2022-05-09 at 4.36.10 PM.png…]()

2. In my personal Teams environment, the XSOAR BOT never installs. I get the following error:
![Uploading Screenshot 2022-05-05 at 9.04.58 PM.png…]()

We have provided all roles, if not more, to the BOT created. Furthermore, the app integration needed tenant ID and URL to be added after the BOT ID for the integration to started working.

We need help with the above customer issue ASAP and need the documentation updated to include this scenario.

**Comment by rpriyanka-sa** [comment]
@A-Musa For your reference too

**Comment by A-Musa** [comment]
hi @anara123 , FYI . Is there someone we can work with on this. This is for a big deal with a Major insurance company. Thank you

**Comment by bakatzir** [comment]
@rpriyanka-sa this repo is meant to have community issues that personnel can take and contrib to the MP, please work via support to report and handle defects, as the template for this issues suggests.
