### ISSUE TITLE
Support for Vertex Enterprise with Optic

### ISSUE THREAD

**Issue by bertdg** [demisto/content#19204]
Hello,

I believe that in order to authenticate to a REST API of an Enterprise Synapse with Optic the base URL needs to be modified from:

https://github.com/demisto/content/blob/e1c26879d309aa84c5aa27c30a0ff3bc4f7905d8/Packs/Synapse/Integrations/Synapse/Synapse.py#L844

```
<         base_url = urljoin(base, '/api/v1')
>         base_url = urljoin(base, '/api/v1/optic')
```

Reference:
https://optic.docs.vertex.link/en/latest/search.html?q=login&check_keywords=yes&area=default

One suggestion would be a configuration option that the Synapse being connected to is running Optic or not. And if it is the login url needs to be updated.

I will attempt a pull request for review if thats an option.

Thank you

**Comment by bakatzir** [comment]
Contributing to the marketplace is always a most welcomed option. Happy to see your commits in the Marketplace!
