### ISSUE TITLE
Incident name isn't updated without refreshing the page after changing it in the CLI 

### ISSUE THREAD

**Issue by amirkhayat** [demisto/content#197]
When Changing incident name in the CLI the incident name in the top of the page isn't updated without refreshing the page

**Comment by Spivaka** [comment]
@amirkhayat are you sure this belong here?

**Comment by amirkhayat** [comment]
@Spivaka I guess I clicked on open issue when I was under "content" no it is not, it is by mistake I will reopen it under server
