### ISSUE TITLE
pan-os-check-logs-status is broken by this line

### ISSUE THREAD

**Issue by alujones** [demisto/content#20102]
https://github.com/demisto/content/blob/61e32a36e178c9b01fc1dd44b5038371d2deb65d/Packs/PAN-OS/Integrations/Panorama/Panorama.py#L11222

19 days ago, this line was changed, to go from passing "args.get('job_id')" (a string) to passing "args" (a dict) as the sole parameter to panorama_check_logs_status_command.

The corresponding changes were NOT made to the function panorama_check_logs_status:

https://github.com/demisto/content/blob/61e32a36e178c9b01fc1dd44b5038371d2deb65d/Packs/PAN-OS/Integrations/Panorama/Panorama.py#L4706

panorama_check_logs_status expects a string, not a dict.

As a result, every call we make to the pan-os-check-logs-status command returns "Query timed out" even when called immediately after submitting the query, or when waiting for a query to give a successful result.

This wasted a lot of time. Please ensure that this is fixed, and that there is a unit test, or at the very least, a check for exceptions, in place to catch this sort of thing in future.

![image](https://user-images.githubusercontent.com/44477039/179628800-c00b0863-2f97-455b-a527-6b9ae26c64c9.png)

**Comment by bakatzir** [comment]
Please open issues via TAC team and not in this repo, as the template suggests.
