### ISSUE TITLE
util content list

### ISSUE THREAD

**Issue by meirwah** [demisto/content#202]
math
- [ ] equals
- [ ] less_than_percentage
- [ ] compare_numbers
- [ ] divide_numbers
- [ ] generate_uuid
- [ ] multiply_numbers
- [ ] random_number_generator
- [ ] round
- [ ] subtract_numbers
 
date
- [ ] get_time
- [ ] offset_time_by
- [ ] parse_date

Filesystem
- [ ] add_text_to_file
- [ ] copy
- [ ] create_folder
- [ ] delete
- [ ] move
- [ ] read_from_file
- [ ] unzip_archive
- [ ] write_to_file
- [ ] zip_folder
 
HTTP
- [ ] get
- [ ] post
- [ ] delete
- [ ] get_header_value
- [ ] url_encoder
- [ ] verify_url_is_accessible

Lists
- [ ] add_element
- [ ] check_list_type
- [ ] compare_lists
- [ ] contains
- [ ] convert_list_to_string
- [ ] find_all
- [ ] get_by_index
- [ ] length
- [ ] prepend_element
- [ ] remove_by_index
- [ ] sort_list
- [ ] trim_list

json
- [ ] add_json_property_to_object
- [ ] add_object_into_json_array
- [ ] json_path_query
- [ ] validate_json

Network
- [ ] ping
- [ ] wait_port_open

OS
- [ ] get OS

print 
- [ ] print

strings
- [ ] append
- [ ] filter_lines
- [ ] length
- [ ] match_regex
- [ ] regex_replace
- [ ] remove
- [ ] search_and_replace
- [ ] string_equals
- [ ] string_occurrence_counter
- [ ] substring
- [ ] trim
- [ ] extract Hash/ip/url/domain from text

other
- [ ] base64_decoder
- [ ] base64_encoder
- [ ] sleep
- [ ] is_true

xml
- [ ] add_attribute
- [ ] convert_xml_to_json
- [ ] convert_json_to_xml
- [ ] set_value
- [ ] xpath_query
- [ ] validate

SCP 
- [ ] copy_to
- [ ] copy_from

**Comment by meirwah** [comment]
@liorkol

**Comment by slavikm** [comment]
@meirwah @liorkol I started doing something a while ago at #193 - please make sure to review before running with this

**Comment by meirwah** [comment]
@slavikm I think it is better to split it to small scripts,
so user can easily drag and drop his tasks logic, WDYT?

**Comment by slavikm** [comment]
@meirwah maybe - will leave it for you guys to decide but then you'll have huge amount of small scripts...

**Comment by meirwah** [comment]
moved to https://github.com/demisto/server/issues/5703
