### ISSUE TITLE
[TAXII2 Server] Error while parsing correct date time value for Added After parameter

### ISSUE THREAD

**Issue by nijrajgelani-crest** [demisto/content#21349]
TAXII2 Server is erroring out when queried with the following error:
```
Could not perform the objects request: Added after time format should be YYYY-MM-DDTHH:mm:ss.[s+]Z. time data '2022-09-17T06:12:39Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
```

According to the [TAXII2 Specifications](http://docs.oasis-open.org/cti/taxii/v2.0/cs01/taxii-v2.0-cs01.html#_Toc496542710),

> The timestamp field MUST be a valid RFC 3339-formatted timestamp [[RFC3339](http://docs.oasis-open.org/cti/taxii/v2.0/cs01/taxii-v2.0-cs01.html#kix.dxm6kbk8toqp)] using the format YYYY-MM-DDTHH:mm:ss.[s+]Z where the “s+” represents 1 or more sub-second values. The brackets denote that sub-second precision is optional, and that if no digits are provided, the decimal place MUST NOT be present.

So `2022-09-17T06:12:39Z` without the sub-second precision is a valid input but the TAXII2 Server integration is expecting the sub-second precision to always be there (https://github.com/demisto/content/blob/master/Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.py#L841).

**Comment by bakatzir** [comment]
closing as fixed.
