### ISSUE TITLE
URLScan.io XSIAM (XSOAR) issue

### ISSUE THREAD

**Issue by Forrest-Stevens** [demisto/content#22300]
Hi, 

Having an issue with trying to leverage the URLScan.io integration. https://cortex.marketplace.pan.dev/marketplace/details/UrlScan/ 

We're running into issues where there is a fail when we try to use the !url command, for instance trying to type without "http://www.xyz" we get a reason error "use_url_as_name". 
<img width="351" alt="image" src="https://user-images.githubusercontent.com/99199868/202219266-127d2d4c-68ec-4ac8-b1f4-4c63b1389419.png">

When continuing the documentation and trying to leverage the full url (with http/https) we receive an issue of "not enough values to unpack (expected 3, got 2)".
<img width="573" alt="image" src="https://user-images.githubusercontent.com/99199868/202219354-fa0c21b4-5572-4e54-91a2-a4bd87a7e850.png">

We reached out to Palo Alto who informed us to reach out to URLScan who informed us to open an issue here and tag @randomizerxd as they introduced the change. 

Any assistance, or even simply a statement that the support for it is discontinued, is appreciated.

**Comment by randomizerxd** [comment]
Hi @Forrest-Stevens, I am aware of this issue and have implemented a fix in PR [22242](https://github.com/demisto/content/pull/22242)

**Comment by dorschw** [comment]
@Forrest-Stevens, thanks for opening an issue. @randomizerxd 's solution PR has been merged, so the fix should be available in the marketplace within 24 hours.
