### ISSUE TITLE
Issue with the QRadar Get Offense Logs playbook's StartTime formatter

### ISSUE THREAD

**Issue by youssefhabri** [demisto/content#22610]
Hello,

There seems to be an issue with this date format used in QRadar Get Offense Logs playbook's StartTime formatter:
https://github.com/demisto/content/blob/1a11b356235998bff0f270a5433c0dc1451b6836/Packs/QRadar/Playbooks/playbook-QRadar_-_Get_Offense_Logs.yml#L228

This will fail to parse on anything that doesn't end with `+00:00`, which could happen if the date happened to be in a different timezone.

Unless I'm misunderstanding something, I think the format should be changed to `'%Y-%m-%dT%H:%M:%S.%f%z'`

**Comment by youssefhabri** [comment]
After looking at it again, it seems that no matter what format string is used, it will fail at some point, because QRadar sometimes returns time with milliseconds, and sometimes it doesn't.

What I'm wondering however is why do we even need a formatter string, when the underlying code can automatically detect the format on its own? 🤔

**Comment by bakatzir** [comment]
ssues should only be opened by the repository maintainers.

Bugs should be reported to customer support and feature requests should be created in [AHA](https://xsoar.ideas.aha.io/).
