### ISSUE TITLE
Invalid Client ID

### ISSUE THREAD

**Issue by dsampson01** [demisto/content#22878]
Upon double-clicking the DBot button on your web site to install, I receive an error that is displayed at the Slack web site as shown in the attached screen capture. It complains about an invalid client_id parameter. Not sure what else to do except to report.
![2022-12-08 13_18_08-Clipboard](https://user-images.githubusercontent.com/4681377/206571744-24c360e5-f1d9-46ae-a0f0-a4fb6f06fa89.png)

**Comment by bakatzir** [comment]
Issues should only be opened by the repository maintainers.

Bugs should be reported to customer support and feature requests should be created in [AHA](https://xsoar.ideas.aha.io/).

Please do not open this issue.
