### ISSUE TITLE
[RTIR Integration] Error setting custom fields with rtir-edit-ticket

### ISSUE THREAD

**Issue by eqave** [demisto/content#25494]
This generates the error "Failed to edit ticket".

https://github.com/demisto/content/blob/57d15da240d6e9a37a7a5f9d7d79342b3fdd2d1d/Packs/RTIR/Integrations/RTIR/RTIR.py#L485

To replicate, run:

`!rtir-edit-ticket ticket-id=###### status=new customfields=field=value`

**Comment by eqave** [comment]
Some additional details...

If you change the line above to this, the issue is resolved:
`content = content +'\n' + key + value`

Additionally, adding this line resolves a separate issue where the rtir-edit-ticket command returns with "No arguments were given to edit the ticket." even when customfields is supplied:
```
customfields = demisto.args().get('customfields')
if customfields:
    arguments_given = True            # Add this line.
    cf_list = customfields.split(',')
    for cf in cf_list:
        equal_index = cf.index('=')
        key = 'CF-{}: '.format(cf[:equal_index])
        value = cf[equal_index + 1:]
```

**Comment by bakatzir** [comment]
please open a support ticket at https://support.paloaltonetworks.com/Support/Index
