### ISSUE TITLE
Export to CSV option is not working for markdown table in XSOAR incident layout

### ISSUE THREAD

**Issue by crestdatasystems** [demisto/content#25827]
The issue with exporting the markdown table containing links to CSV format in the XSOAR incident layout.

We're experiencing an issue with exporting a markdown table that contains multiple name bindings with URLs from Demisto to CSV format. Specifically, the names that are linked to URLs(Hyperlinks) do not export properly, and I'm not able to access the links in the CSV file.

I've attached some screenshots to help illustrate the problem. Has anyone else encountered this issue before, and if so, do you have any insights or solutions that you could share? This seems more like an issue with the export to CSV functionality.

![csv_file](https://user-images.githubusercontent.com/60967033/231741275-7d997072-fa02-4bbc-b7d2-370cd84754a5.png)
![export_to_csv](https://user-images.githubusercontent.com/60967033/231741305-866e9f7e-6911-425e-9763-d0c2ccf51fc6.png)

**Comment by bakatzir** [comment]
please open a support ticket at https://support.paloaltonetworks.com/Support/Index
