### ISSUE TITLE
Errors with retrieval from context

### ISSUE THREAD

**Issue by shaniacht1** [demisto/content#428]
![image](https://cloud.githubusercontent.com/assets/24434391/25672091/f2cee14a-303a-11e7-8bf6-64289fa31b3b.png)

---

![image](https://cloud.githubusercontent.com/assets/24434391/25672133/13680490-303b-11e7-87c8-8aed76cca40b.png)

---

Seems like there is an error with retrieval of information from context in the CLI (also from playbooks)
Both images show a different error but seem to be related.

**Comment by dorsha** [comment]
Moving to other repository.
