### ISSUE TITLE
Allow demisto to import cloudslang content

### ISSUE THREAD

**Issue by lrevnic** [demisto/content#8]
CloudSlang is a generic orchestrator tool. The proposal is to allow Demisto to consume CloudSlang content. In this way both platforms will benefit of the extensive list of CloudSlang content
https://github.com/CloudSlang/cloud-slang-content

**Comment by meirwah** [comment]
@lrevnic that does makes sense.. adding both CloudSlang and OO integration (using content) to expand Demisto capabilities.
But at this moment it is not at our top priority, so we don't plan to impl soon, but if you want to add this capability ... :)
